/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test_create" instead.
 */

#include "test.h"

START_TEST(Distribution_function_1) {
  /*
    НЕОБХОДИМЫЙ ТЕСТ

    Тест для распределения Хьюбера
    Параметр формы: 0.5
    Параметр сдвига: 0
    Параметр масштаба: 1
  */

  ck_assert_double_eq_tol(HuberDistributionDensity(0, 0.5, 0, 1), 0.223, 3);
  ck_assert_double_eq_tol(HuberDistributionMathExpectation(0.5, 0, 1), 0, 3);
  ck_assert_double_eq_tol(HuberDistributionVariation(0.5, 0, 1), 8.08, 2);
  ck_assert_double_eq_tol(HuberDistributionSkewness(0.5, 0, 1), 0, 3);
  ck_assert_double_eq_tol(HuberDistributionKurtosis(0.5, 0, 1), 2.94, 3);
}

START_TEST(Distribution_function_2) {
  /*
    Тест для распределения Хьюбера
    Параметр формы: 3
    Параметр сдвига: 0
    Параметр масштаба: 1
  */

  ck_assert_double_eq_tol(HuberDistributionDensity(0, 3, 0, 1), 0.339, 3);
  ck_assert_double_eq_tol(HuberDistributionMathExpectation(3, 0, 1), 0, 3);
  ck_assert_double_eq_tol(HuberDistributionVariation(3, 0, 1), 1.00, 2);
  ck_assert_double_eq_tol(HuberDistributionSkewness(3, 0, 1), 0, 3);
  ck_assert_double_eq_tol(HuberDistributionKurtosis(3, 0, 1), 0.04, 2);
}

START_TEST(Distribution_function_3) {
  /*
    Тест для распределения Хьюбера
    Параметр формы: 3
    Параметр сдвига: 100
    Параметр масштаба: 1
  */

  ck_assert_double_eq_tol(HuberDistributionDensity(0, 3, 100, 1), 0.339, 3);
  ck_assert_double_eq_tol(HuberDistributionMathExpectation(3, 100, 1), 100, 3);
  ck_assert_double_eq_tol(HuberDistributionVariation(3, 100, 1), 1.00, 2);
  ck_assert_double_eq_tol(HuberDistributionSkewness(3, 100, 1), 0, 3);
  ck_assert_double_eq_tol(HuberDistributionKurtosis(3, 100, 1), 0.04, 2);
}

START_TEST(Distribution_function_4) {
  /*
    Тест для распределения Хьюбера
    Параметр формы: 3
    Параметр сдвига: 0
    Параметр масштаба: 0.5
  */

  ck_assert_double_eq_tol(HuberDistributionDensity(0, 3, 0, 0.5), 0.797, 3);
  ck_assert_double_eq_tol(HuberDistributionMathExpectation(3, 0, 0.5), 0, 3);
  ck_assert_double_eq_tol(HuberDistributionVariation(3, 0, 0.5), 1.004, 3);
  ck_assert_double_eq_tol(HuberDistributionSkewness(3, 0, 0.5), 0, 3);
  ck_assert_double_eq_tol(HuberDistributionKurtosis(3, 0, 0.5), 45.6389, 4);
}

START_TEST(Distribution_function_5) {
  /*
    НЕОБХОДИМЫЙ ТЕСТ

    Тест для распределения Хьюбера
    Параметр формы: 2
    Параметр сдвига: 10
    Параметр масштаба: 2
  */

  ck_assert_double_eq_tol(HuberDistributionDensity(0, 2, 10, 2), 6.63517e-05,
                          3);
  ck_assert_double_eq_tol(HuberDistributionMathExpectation(2, 10, 2), 10, 3);
  ck_assert_double_eq_tol(HuberDistributionVariation(2, 10, 2), 4.32, 2);
  ck_assert_double_eq_tol(HuberDistributionSkewness(2, 10, 2), 0, 3);
  ck_assert_double_eq_tol(HuberDistributionKurtosis(2, 10, 2), -2.7805, 4);
}

START_TEST(Distribution_mix_1) {
  /*
    Тест для смеси Хьюберов
    Параметры формы: 2.5 | 2.5
    Параметры сдвига: 2 | 2
    Параметры масштаба: 2 | 2
    Параметр смеси: 0.7
  */
  double x = 0;
  double y_1 = 2.5, y_2 = 2.5;
  double mu_1 = 2, mu_2 = 2;
  double lambda_1 = 2, lambda_2 = 2;
  double p = 0.7;

  ck_assert_double_eq_tol(
      HuberMixtureDencity(0, p, y_1, y_2, mu_1, mu_2, lambda_1, lambda_2),
      HuberDistributionDensity(0, y_1, mu_1, lambda_1), 3);
  ck_assert_double_eq_tol(
      HuberMixtureMathExpectation(p, y_1, y_2, mu_1, mu_2, lambda_1, lambda_2),
      HuberDistributionMathExpectation(y_1, mu_1, lambda_1), 3);
  ck_assert_double_eq_tol(
      HuberMixtureVariation(p, y_1, y_2, mu_1, mu_2, lambda_1, lambda_2),
      HuberDistributionVariation(y_1, mu_1, lambda_1), 3);
  ck_assert_double_eq_tol(
      HuberMixtureSkewness(p, y_1, y_2, mu_1, mu_2, lambda_1, lambda_2),
      HuberDistributionSkewness(y_1, mu_1, lambda_1), 3);
  ck_assert_double_eq_tol(
      HuberMixtureKurtosis(p, y_1, y_2, mu_1, mu_2, lambda_1, lambda_2),
      HuberDistributionKurtosis(y_1, mu_1, lambda_1), 3);
}

START_TEST(Distribution_mix_2) {
  /*
    Тест для смеси Хьюберов (мат.ожидание)
    Параметры формы: 2 | 2
    Параметры сдвига: 2 | 6
    Параметры масштаба: 2 | 2
    Параметр смеси: 0.3
  */
  double x = 0;
  double y_1 = 1, y_2 = 2;
  double mu_1 = 2, mu_2 = 6;
  double lambda_1 = 2, lambda_2 = 8;
  double p = 0.8;

  ck_assert_double_eq_tol(
      HuberMixtureMathExpectation(p, y_1, y_2, mu_1, mu_2, lambda_1, lambda_2),
      4, 3);
}

START_TEST(Distribution_mix_3) {
  /*
    Тест для смеси Хьюберов (дисперсия)
    Параметры формы: 2 | 2
    Параметры сдвига: 0 | 0
    Параметры масштаба: 2 | 2
    Параметр смеси: 0.5
  */
  double x = 0;
  double y_1 = 2, y_2 = 2;
  double mu_1 = 0, mu_2 = 0;
  double lambda_1 = 1, lambda_2 = 3;
  double p = 0.5;

  ck_assert_double_eq_tol(
      HuberMixtureVariation(p, y_1, y_2, mu_1, mu_2, lambda_1, lambda_2),
      5.401523, 4);
}

END_TEST

Suite *suite_Huber_Destr() {
  Suite *s1 = suite_create(YELLOW_BG BLACK "Huber_Destr" RESET);
  TCase *tc1_1 = tcase_create("Huber_Destr");

  tcase_add_test(tc1_1, Distribution_function_1);
  tcase_add_test(tc1_1, Distribution_function_2);
  tcase_add_test(tc1_1, Distribution_function_3);
  tcase_add_test(tc1_1, Distribution_function_4);
  tcase_add_test(tc1_1, Distribution_function_5);
  tcase_add_test(tc1_1, Distribution_mix_1);
  tcase_add_test(tc1_1, Distribution_mix_2);
  tcase_add_test(tc1_1, Distribution_mix_3);

  suite_add_tcase(s1, tc1_1);

  return s1;
}
